# config.yml 文件示例

settings:
  exit-point: "world,0,64,0,0,0"

dungeons:
  # 普通副本示例
  dungeon_normal_1:
    type: "normal"
    level-required: 0
    max-players: 4
    spawn-point: "world,100,64,100,0,0"
    death-waiting-area: "world,110,64,110,0,0"
    target-mob: "boss_goblin_king"
    mobs:
      - id: "dungeon_goblin"
        location: "world,120,64,120,0,0"
      - id: "dungeon_goblin"
        location: "world,125,64,125,0,0"
      - id: "dungeon_goblin_elite"
        location: "world,130,64,130,0,0"
      - id: "boss_goblin_king"
        location: "world,140,64,140,0,0"

  # 波次副本示例
  dungeon_wave_1:
    type: "wave"
    level-required: 10
    max-players: 5
    spawn-point: "world,200,64,200,0,0"
    death-waiting-area: "world,210,64,210,0,0"
    target-mob: "boss_dragon"  # 最终Boss (如果有的话)
    # 初始怪物，可选
    mobs:
      - id: "dungeon_guide"
        location: "world,205,64,205,0,0"
    # 波次配置
    waves:
      total: 3  # 总波数
      # 第一波怪物
      wave-1:
        - id: "dungeon_skeleton"
          location: "world,220,64,220,0,0"
        - id: "dungeon_skeleton"
          location: "world,225,64,225,0,0"
        - id: "dungeon_skeleton"
          location: "world,230,64,230,0,0"
      # 第二波怪物
      wave-2:
        - id: "dungeon_zombie"
          location: "world,240,64,240,0,0"
        - id: "dungeon_zombie"
          location: "world,245,64,245,0,0"
        - id: "dungeon_zombie_elite"
          location: "world,250,64,250,0,0"
        - id: "dungeon_zombie_elite"
          location: "world,255,64,255,0,0"
      # 第三波怪物 (最后一波)
      wave-3:
        - id: "dungeon_skeleton_elite"
          location: "world,260,64,260,0,0"
        - id: "dungeon_zombie_elite"
          location: "world,265,64,265,0,0"
        - id: "boss_dragon"  # 最终Boss
          location: "world,270,64,270,0,0"

  # 另一个波次副本示例 (只有波次，没有最终Boss)
  dungeon_wave_survival:
    type: "wave"
    level-required: 20
    max-players: 4
    spawn-point: "world,-100,64,-100,0,0"
    death-waiting-area: "world,-110,64,-110,0,0"
    waves:
      total: 5  # 总波数
      # 第一波
      wave-1:
        - id: "dungeon_spider"
          location: "world,-120,64,-120,0,0"
        - id: "dungeon_spider"
          location: "world,-125,64,-125,0,0"
      # 第二波
      wave-2:
        - id: "dungeon_spider"
          location: "world,-130,64,-130,0,0"
        - id: "dungeon_spider"
          location: "world,-135,64,-135,0,0"
        - id: "dungeon_spider_elite"
          location: "world,-140,64,-140,0,0"
      # 第三波
      wave-3:
        - id: "dungeon_spider_elite"
          location: "world,-145,64,-145,0,0"
        - id: "dungeon_spider_elite"
          location: "world,-150,64,-150,0,0"
      # 第四波
      wave-4:
        - id: "dungeon_cave_spider"
          location: "world,-155,64,-155,0,0"
        - id: "dungeon_cave_spider"
          location: "world,-160,64,-160,0,0"
        - id: "dungeon_cave_spider"
          location: "world,-165,64,-165,0,0"
      # 第五波
      wave-5:
        - id: "dungeon_spider_queen"
          location: "world,-170,64,-170,0,0"
        - id: "dungeon_spider_elite"
          location: "world,-175,64,-175,0,0"
        - id: "dungeon_spider_elite"
          location: "world,-180,64,-180,0,0"