# config.yml 文件示例
dungeon-rewards:
  # 啟用獎勵標準檢查
  enabled: true

  # 全域設定
  global:
    # 傷害標準倍數（會乘以最高輸出玩家的傷害作為獎勵門檻）
    damage-threshold-multiplier: 0.5

    # 是否顯示獎勵資格訊息
    show-reward-eligibility: true

    # 獎勵標準訊息設定
    messages:
      reward-qualified: "§a§l恭喜！你已達到獎勵標準！"
      reward-not-qualified: "§c很遺憾，你的傷害未達到獎勵標準（需要達到最高輸出的 {threshold}%）"
      damage-threshold-info: "§e本次獎勵門檻：{threshold} 傷害（最高輸出的 {percentage}%）"

  # 特定副本設定（覆蓋全域設定）
  dungeons:
    # 範例副本 1 - 較低門檻
    "wave_dungeon_1":
      damage-threshold-multiplier: 0.3

    # 範例副本 2 - 標準門檻
    "wave_dungeon_2":
      damage-threshold-multiplier: 0.5

    # 困難副本 - 較高門檻
    "hard_dungeon":
      damage-threshold-multiplier: 0.8
key-settings:
  # 鑰匙使用冷卻時間（秒）
  # 預設值：180 (3分鐘)
  cooldown-seconds: 180
  # 新增：冷卻完成通知設定
  cooldown-complete-sound: "ENTITY_PLAYER_LEVELUP"  # 冷卻完成音效
  cooldown-complete-volume: 1.0  # 音效音量
  cooldown-complete-pitch: 1.0   # 音效音調

  # 可選：是否預設開啟通知（如果不設定，預設為開啟）
  default-notification-enabled: true

  # 可選：通知訊息自定義
  notification-message: "§a§l[副本系統] §f你的副本入場卷冷卻已完成！可以再次使用了"
  notification-title: "§a副本入場卷"
  notification-subtitle: "§f冷卻完成！"

settings:
  exit-point: "world,0,64,0,0,0"
  revival-system-enabled: true
ranking:
  hologram-update-interval: 5 # 自動更新間隔（秒）
wave-dungeon:
  force-next-wave-countdown: 300
  sounds:
    countdown: "BLOCK_NOTE_BLOCK_PLING"
    wave-start: "ENTITY_ENDER_DRAGON_GROWL"
    wave-clear: "ENTITY_PLAYER_LEVELUP"
    dungeon-complete: "UI_TOAST_CHALLENGE_COMPLETE"
    force-next-wave: "BLOCK_ANVIL_LAND"  # 新增：強制下一波音效
  sound-options:
    volume: 1.0
    pitch: 1.0
    countdown-pitch: 1.2
    force-next-wave-pitch: 0.8  # 新增：強制下一波音效的音調
mob-scaling:
  # 普通怪物數量倍率（根據玩家數量）
  normal-multipliers:
    "1": 1.0    # 1人時，怪物數量 × 1.0
    "2": 2.0    # 2人時，怪物數量 × 2.0
    "3": 3.0    # 3人時，怪物數量 × 3.0
    "4": 4.0    # 4人時，怪物數量 × 4.0

  # BOSS等級加成（根據玩家數量）
  boss-level-bonus:
    "1": 0      # 1人時，BOSS等級 +0
    "2": 5      # 2人時，BOSS等級 +5
    "3": 10     # 3人時，BOSS等級 +10
    "4": 15     # 4人時，BOSS等級 +15
dungeons:
  # 普通副本示例
  dungeon_normal_1:
    type: "normal"
    level-required: 0
    max-players: 4
    spawn-point: "world,100,64,100,0,0"
    death-waiting-area: "world,110,64,110,0,0"
    target-mob: "boss_goblin_king"
    mobs:
      - id: "dungeon_goblin"
        location: "world,120,64,120,0,0"
      - id: "dungeon_goblin"
        location: "world,125,64,125,0,0"
      - id: "dungeon_goblin_elite"
        location: "world,130,64,130,0,0"
      - id: "boss_goblin_king"
        location: "world,140,64,140,0,0"

  # 波次副本示例
  dungeon_wave_1:
    type: "wave"
    level-required: 10
    max-players: 5
    spawn-point: "world,200,64,200,0,0"
    death-waiting-area: "world,210,64,210,0,0"
    modify: false #預設為true，此副本是否需要根據人數提升難度
    target-mob: "boss_dragon"  # 最终Boss (如果有的话)
    # 初始怪物，可选
    mobs:
      - id: "dungeon_guide"
        location: "world,205,64,205,0,0"
    # 波次配置
    waves:
      total: 3  # 总波数
      # 第一波怪物
      wave-1:
        - id: "dungeon_skeleton"
          location: "world,220,64,220,0,0"
        - id: "dungeon_skeleton"
          location: "world,225,64,225,0,0"
        - id: "dungeon_skeleton"
          location: "world,230,64,230,0,0"
      # 第二波怪物
      wave-2:
        - id: "dungeon_zombie"
          location: "world,240,64,240,0,0"
        - id: "dungeon_zombie"
          location: "world,245,64,245,0,0"
        - id: "dungeon_zombie_elite"
          location: "world,250,64,250,0,0"
        - id: "dungeon_zombie_elite"
          location: "world,255,64,255,0,0"
      # 第三波怪物 (最后一波)
      wave-3:
        - id: "dungeon_skeleton_elite"
          location: "world,260,64,260,0,0"
        - id: "dungeon_zombie_elite"
          location: "world,265,64,265,0,0"
        - id: "boss_dragon"  # 最终Boss
          location: "world,270,64,270,0,0"

  # 另一个波次副本示例 (只有波次，没有最终Boss)
  dungeon_wave_survival:
    type: "wave"
    level-required: 20
    max-players: 4
    spawn-point: "world,-100,64,-100,0,0"
    death-waiting-area: "world,-110,64,-110,0,0"
    waves:
      total: 5  # 总波数
      # 第一波
      wave-1:
        - id: "dungeon_spider"
          location: "world,-120,64,-120,0,0"
        - id: "dungeon_spider"
          location: "world,-125,64,-125,0,0"
      # 第二波
      wave-2:
        - id: "dungeon_spider"
          location: "world,-130,64,-130,0,0"
        - id: "dungeon_spider"
          location: "world,-135,64,-135,0,0"
        - id: "dungeon_spider_elite"
          location: "world,-140,64,-140,0,0"
      # 第三波
      wave-3:
        - id: "dungeon_spider_elite"
          location: "world,-145,64,-145,0,0"
        - id: "dungeon_spider_elite"
          location: "world,-150,64,-150,0,0"
      # 第四波
      wave-4:
        - id: "dungeon_cave_spider"
          location: "world,-155,64,-155,0,0"
        - id: "dungeon_cave_spider"
          location: "world,-160,64,-160,0,0"
        - id: "dungeon_cave_spider"
          location: "world,-165,64,-165,0,0"
      # 第五波
      wave-5:
        - id: "dungeon_spider_queen"
          location: "world,-170,64,-170,0,0"
        - id: "dungeon_spider_elite"
          location: "world,-175,64,-175,0,0"
        - id: "dungeon_spider_elite"
          location: "world,-180,64,-180,0,0"